# The name of this application, which must be unique within a project.
name: 'app'

# The type key specifies the language and version for your application.
type: "nodejs:6.9"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mydatabase:mongodb"

# The hooks that will be triggered when the package is deployed.
hooks:
    # Build hooks can modify the application files on disk but not access any services like databases.
    build: |
      cd ./build
      tar -xf platformsh-example-meteor.tar.gz
      cd bundle
      (cd ./programs/server && npm install)

    # Deploy hooks can access services but the file system is now read-only.
    deploy: |


# The size of the persistent disk of the application (in MB).
disk: 512

# The 'mounts' describe writable, persistent filesystem mounts in the application.
# The keys are directory paths relative to the application root. The values are
# strings such as 'shared:files/NAME' where NAME is just a unique name for the mount.
mounts:
  "/run": "shared:files/run"

# The configuration of the application when it is exposed to the web.
web:
    commands:
      start: "node index.js"
    locations:
      "/public":
        passthru: false
        root: "public"
        # Whether to allow files not matching a rule or not.
        allow: true
        rules:
          '\.png$':
            allow: true
            expires: -1
